#[Info]
site_name: YFei's Blog
site_url: https://fjash.github.io
site_author: YFei
#[UI]
theme:
  name: material
  language: zh
  font:
  text: LXGW WenKai Screen GB Screen # Share Tech
  code: JetBrains Mono
palette:
  scheme: default
  primary: brown
  accent: deep orange
  features:
    - content.code.annotate
    - content.code.copy
    # - navigation.instant # This will cause LaTeX render fail at the first try.
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    # - navigation.prune