site_name: fjash's Blog
site_author: fjash
site_url: https://fjash.github.io

repo_name: 'fjash/fjash.github.io'
repo_url: 'https://github.com/fjash/fjash.github.io'
edit_uri: blob/main/docs

theme:
  name: material
  language: zh
  favicon: _assets/iro/IroPatch_Pink.ico
  font:
    text: LXGW WenKai Screen GB Screen # Share Tech
    code: JetBrains Mono
  palette: # 调色板
      # Palette toggle for light mode
      - scheme: default
        toggle:
          icon: material/brightness-7 
          name: Switch to dark mode

      # Palette toggle for dark mode
      - scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    # - navigation.instant # This will cause LaTeX render fail at the first try.
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    # - navigation.prune


copyright: 'Copyright &copy 2024 YFei'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fjash
      name: Github


nav:
  - "💠 封面": index.md
  # - "📚 技术积累":
  #   - "编程语言":
  #     - "C++": 
  #     - "Python":
  #     - "C":
  #   - "人工智能":
  #     - "机器学习":
  #     - "深度学习":
  #     - "常见模型":
  #     - "代码框架":
  #       - "Pytorch":
  - "🥎 算法题练习":
    - "Leetcode": docs\mds\Algorithnm\Leetcode\Leetcode_1.md
  # - "📝 论文阅读":
  # - "📦 杂项专题":